folder:
  path: /Users/lucasdossantos/Desktop/gpaCsv/
  csvChefe: user_import_chefe.csv
  csvVendedor: user_import_vendedor.csv
  zipChefe: IcParticipantDetailChefe.zip
  zipVendedor: IcParticipantDetailVendedor.zip

client:
  defaultUriIntegrationService: https://ehhs-test.fa.la1.oraclecloud.com:443/fscmService/ErpIntegrationService
  defaultUriMktImport: https://ehhs-test.fa.la1.oraclecloud.com:443/crmService/ImportPublicService
  user:
    name: marcelo.taboada@oracle.com
    password: gpa12345

mktImport:
  defaultUri: https://ehhs-test.fa.la1.oraclecloud.com:443/crmService/ImportPublicService
  submitImportActivity:
    xmlnsFather:
      name: http://xmlns.oracle.com/oracle/apps/marketing/commonMarketing/mktImport/model/types/
      prefix: typ
      localPart:
         - submitImportActivity
    xmlnsChild:
      name: http://xmlns.oracle.com/oracle/apps/marketing/commonMarketing/mktImport/model/
      prefix: mod
      localPart:
        - HeaderRowIncluded
        - MappingNumber
        - Delimiter
        - FileFormat
        - FileContent
      values:
        - Y
        - 300000001723186
        - ;
        - OTHER_DELIMITER
  getImportActivityStatus:
    xmlnsFather:
      name: http://xmlns.oracle.com/oracle/apps/marketing/commonMarketing/mktImport/model/types/
      prefix: typ
      localPart:
        - getImportActivityStatus
      values:
    xmlnsChild:
      name:
      prefix:
      localPart:
      values:


uploadFileToUcm:
  defaultUri: https://ehhs-test.fa.la1.oraclecloud.com:443/fscmService/ErpIntegrationService
  upload:
    xmlnsFather:
      name: http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/
      prefix: erp
      localPart:
        - uploadFileToUcm
      values:
    xmlnsChild:
      name: http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/
      prefix: erp
      localPart:
        - DocumentTitle
        - DocumentAuthor
        - DocumentSecurityGroup
        - DocumentAccount
        - DocumentName
      values:


essJobs:
  defaultUri: https://ehhs-test.fa.la1.oraclecloud.com:443/fscmService/ErpIntegrationService
  xmlns:
    value: http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/
    prefix: typ
  local-part:
    getESSJobStatus: getESSJobStatus
    submitESSJob: submitESSJobRequest
  services:
    sendToLdap:
      jobDefinitionName: CopyPersonalData
      packageName: /oracle/apps/ess/hcm/users/
      arguments:
        - ALL_USERS
      inputs:
    importIncentiveCompensationParticipants:
      jobDefinitionName: ParticipantsImportSQL
      packageName: /oracle/apps/ess/incentiveCompensation/cn/processes/transactionProcess/
      arguments:
        - 300000001064232
        - '#NULL'
        - '#NULL'
        - PARTICIPANT
        - '#NULL'
        - '#NULL'
        - '#NULL'
        - '#NULL'
        - '#NULL'
        - '#NULL'
        - '#NULL'
        - '#NULL'
        - '#NULL'
        - '#NULL'
        - '#NULL'
        - HR_EMPLOYEE
      inputs:
    incentiveCompensationParticipantDetailImport:
      jobDefinitionName: SrpInterfaceLoader
      packageName: /oracle/apps/ess/incentiveCompensation/cn/processes/transactionProcess/
      arguments:
        - archive
        - idArchive
        - N
      inputs:
        - 0
        - 1
    assignRolesToParticipants:
      jobDefinitionName: ParticipantAssignment
      packageName: /oracle/apps/ess/incentiveCompensation/cn/processes/setupProcess/
      arguments:
        - 300000001064232
        - date
        - date
        - NEW
        - ROLE_ASGN
        - '#NULL'
      inputs:









